### ISSUE TITLE
Sin documentar: Estilo de commits

### ISSUE THREAD

**Issue by Jibaru** [idbi/documentation#7]
- Prefijos
- Enlace a las cards
- Enlace a las PR

**Comment by Jibaru** [comment]
build: Cambio que afectan al `build` del sistema o dependencias externas (ejemplos: gulp, broccoli, npm)
ci: Cambios para archivos de configuración de CI y scripts (ejemplos: Travis, Circle, BrowserStack, SauceLabs)
chore: Cambios que no cambian el código fuente o tests. Por ejemplo cambios al proceso de build, herramientas auxiliares, actualizaciones o nuevas dependencias.
docs: Solo cambios en la documentación (por ejemplo, en el README, en storybooks).
feat: Una nueva funcionalidad.
fix: Una corrección de un bug.
perf: Un cambio en el código que mejora la performance
refactor: Un cambio en el código que no corrige un bug ni añade un funcionalidad
revert: Al revertir un cambio :+1: 
style: cambios que no afectan el significado del código (espacios en blanco, formateo, sin ; D:).
test: Para agregar nuevos tests o corregirlos

**Comment by RaillyH** [comment]
- `build`: Cambio que afectan al build del sistema o dependencias externas (ejemplos: gulp, broccoli, npm)
- `ci`: Cambios para archivos de configuración de CI y scripts (ejemplos: Travis, Circle, BrowserStack, SauceLabs)
- `chore`: Cambios que no cambian el código fuente o tests. Por ejemplo cambios al proceso de build, herramientas auxiliares, actualizaciones o nuevas dependencias.
- `docs`: Solo cambios en la documentación (por ejemplo, en el README, en storybooks).
- `feat`: Una nueva funcionalidad.
- `fix`: Una corrección de un bug.
- `perf`: Un cambio en el código que mejora la performance
- `refactor`: Un cambio en el código que no corrige un bug ni añade un funcionalidad
- `revert`: Al revertir un cambio 👍
- `style`: cambios que no afectan el significado del código (espacios en blanco, formateo, sin ; D:).
- `test`: Para agregar nuevos tests o corregirlos

**Comment by Jibaru** [comment]
*Formato del commit:*

El POS-# indica el número de la *card*.

```
<prefijo>: [POS-#] <mensaje>
<descripción?>
```

Ejemplos:

> feat: [POS-10040] handle toppings, discounts and combo extra prices

> feat: [POS-10034] create getExtraComboPrice function
> Some description

Si existen más commits de una card, se pueden ordenar. El primer commit no posee un número, pero se entenderá que es el primero:

> feat: [POS-10034] create getExtraComboPrice function
> feat: [POS-10034-2] update getExtraComboPrice function

**Comment by ZeroBlackErron** [comment]
Ciertas reglas que podriamos seguir a la par:
- Separar el asunto del cuerpo con una línea en blanco
- Limitar la línea de asunto a 50 caracteres
- Poner en mayúscula la primera letra del asunto
- No termine la línea de asunto con un punto
- Use el estado de ánimo imperativo en la línea de asunto
- Envuelva el cuerpo en 72 caracteres
- Usa el cuerpo para explicar qué y por qué versus cómo

Ejemplo:
> Save author in payment when is authenticated
> 
> Modify method to create payment of an order in service to accept
> author (user). Map 'author_uuid' field in payment repository. Use
> queues to send notification when a payment is approved in closed order.
