### ISSUE TITLE
Sin documentar: Formato de PR

### ISSUE THREAD

**Issue by Jibaru** [idbi/documentation#8]
- Título
- La descripción
- Algún Label?
- Assignees?

**Comment by Jibaru** [comment]
Prefijos:
- `HOTFIX`: Para bugs hotfix a prod
- `FIX`: Para bugs que no son hotfix 
- `SYNC`: Para sincronizar ramas (prod y dev).
- `HU`: Para historias de usuario
- `STAR`: Una mejora extra que no es una HU.

Título:
```
[prefijo - POS-#?] Título de la PR
```
ejemplos:
> [HU - POS-9842] Nuevos conceptos tributación Impuesto Bolsa de Plástico
> [HU - POS-9842-2] Nuevos conceptos tributación Impuesto Bolsa de Plástico
> [FIX - POS-9992] TODOS: No actualiza el estado de recepcionado en las ordenes de compra
> [SYNC - POS-9992] TODOS: No actualiza el estado de recepcionado en las ordenes de compra
> [STAR] Mejora cool

**Comment by ZeroBlackErron** [comment]
En vez de prefijos podríamos usar los _labels_.

**Comment by Jibaru** [comment]
> En vez de prefijos podríamos usar los _labels_.

Algún ejemplo o página para checarlos?

**Comment by ZeroBlackErron** [comment]
> Algún ejemplo o página para checarlos?

<img width="280" alt="image" src="https://user-images.githubusercontent.com/40128622/196577346-cdf5bfa1-4dcf-467a-8fda-114e0b61fbb8.png">

**Comment by ZeroBlackErron** [comment]
Sería buena idea usar ambas, tanto los prefijos como los _labels_.

**Comment by ZeroBlackErron** [comment]
Formular un buen nombre para la PR, no solo copiar el título de la card de Youtrack.

**Comment by ZeroBlackErron** [comment]
Propuesta de PR _template_:
```
## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
```

**Comment by ZeroBlackErron** [comment]
De momento, no sería necesario asignar un responsable puesto que la tareas/bugs/_quick wins_ los desarrolla 1 solo persona.

**Comment by ZeroBlackErron** [comment]
Habría que probar usando _milestones_ con tareas grandes.

**Comment by ZeroBlackErron** [comment]
_Template_ acordado:
````
## Motivo (opcional)

## Describe los cambios

## Enlace de Youtrack

## Instrucciones

## Pruebas (capturas)

```

**Comment by Jibaru** [comment]
Labels

- De tipo adicional:
bug: para las cards del tablero de bugs
enhancement: para nuevas tareas
performance: busca una mejorar en el rendimiento
security: Agrega funciones de seguridad

- De tipo de HU:
quick win: para quick wins

- Para solicitar algo:
help wanted: para PR que requieren de una revisión inmediata
pending: para el reviewer cuando solicita cambios al requester
question: cuando se haya solicitado información en la PR

- De estado:
work in progress: Cuando se suba una PR y se siga trabajando en ella
ready for review: Al momento de solicitar una review
ready for merge: Cuando la PR esté aprobada y solo le falta hacer merge

- De PR Cerradas:
duplicate: por si la PR ya existe y se cierra
invalid: para PR inválidas porque no están bien 
wontfix: Cuando se cierra la PR porque no soluciona el problema
stale: Para PR que se realizaron y se cerraron porque nunca se llegó a hacer merge y pasó demasiado tiempo

- Extra
sync: Sincroniza alguna rama

**Comment by ZeroBlackErron** [comment]
Nuevo formato acordado para las PR's:
```
## Motivo

...
> [POS-?](https://youtrack.idbi.pe/issue/POS-?) Título de card en Youtrack

## Describe los cambios

...

## Pruebas

...

```

**Comment by ZeroBlackErron** [comment]
Manejar nuevo prefijo:

- `QW`: Para los quick wins
